server:
  port: 8200

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cred_db?serverTimezone=UTC
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation: none
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml



eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
token:
  access:
    default_time: 1800
  refresh:
    default_time: 86400
