server:
  port: 8761

spring:
  security:
    user:
      password: discPassword
      name: discUser
      roles: SYSTEM
  application:
    name: discovery
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'