server:
  port: 8600

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/order_db?serverTimezone=UTC
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation: none
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml


eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
token:
  access:
    default_time: 1800
  refresh:
    default_time: 86400

security:
  sessions: NEVER
  oauth2:
    client:
      accessTokenUri: http://localhost:8200/oauth/token
      userAuthorizationUri: http://localhost:8200/oauth/authorize
      scope: read, write
      clientId: authserver
      clientSecret: passwordforauthserver
      grant-type: password, refresh_token
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuZhv16CSZ1X11FRQ9x7W
            FPD4w7o7eGlerrbItaJYLm+kF6JZxvY6uqAkrezwCHk8V2JCb3NaYWQc2H4AdGVG
            Edz8ywQOblvGzo0KayD9Hxlt7snXrBNYEKVVB9JfMrzbNyZv8O2utO1bVyc7k286
            LIO1UT5B+S+tifNRG+cIA5RhF7NZiZqjKHrGufgW7Iw+eA/J472qrl5MzBwwJxpN
            6DfkOf5M6ltPgbifNFi5le4cG/aZDebhPzAmMhymxP7rlNz+dBlG3NC8QrF7s3v7
            5AkuJ7iSWqsGYDSXqFR4k1apErbRB51Qwqh6dlJza+OhhNXqdwbvPZLo3M13GQqD
            mwIDAQAB
            -----END PUBLIC KEY----- 