server:
  port: 8500

spring:
  application:
    name: product-service

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  sessions: NEVER
  oauth2:
    client:
      accessTokenUri: http://localhost:8200/oauth/token
      userAuthorizationUri: http://localhost:8200/oauth/authorize
      scope: read, write
      clientId: authserver
      clientSecret: passwordforauthserver
      grant-type: password, refresh_token
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuZhv16CSZ1X11FRQ9x7W
            FPD4w7o7eGlerrbItaJYLm+kF6JZxvY6uqAkrezwCHk8V2JCb3NaYWQc2H4AdGVG
            Edz8ywQOblvGzo0KayD9Hxlt7snXrBNYEKVVB9JfMrzbNyZv8O2utO1bVyc7k286
            LIO1UT5B+S+tifNRG+cIA5RhF7NZiZqjKHrGufgW7Iw+eA/J472qrl5MzBwwJxpN
            6DfkOf5M6ltPgbifNFi5le4cG/aZDebhPzAmMhymxP7rlNz+dBlG3NC8QrF7s3v7
            5AkuJ7iSWqsGYDSXqFR4k1apErbRB51Qwqh6dlJza+OhhNXqdwbvPZLo3M13GQqD
            mwIDAQAB
            -----END PUBLIC KEY----- 
